baseURL = 'https://grey.tertiusfamily.net/'
languageCode = 'en-us'
title = "Greyscale"
theme = 'archie-solarized'
copyright = 'Grey Lathrop'
pygmentsUseClasses = true
pygmentsCodeFences = true

[params]
favicon = "images/robot.png"
mode = "toggle"
useCDN = false

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/plathrop"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/greylathrop/"

[[params.social]]
name = "BlueSky"
icon = "at-sign"
url = "https://bsky.app/profile/greytalyn.bsky.social"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Resume"
url = "https://plathrop.tertiusfamily.net"
weight = 2

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "RSS"
url = "/index.xml"
weight = 5
[[menu.main.params]]
  icon = "rss"
